# Minimal Vault Helm values for development
# Reference: https://developer.hashicorp.com/vault/docs/platform/k8s/helm

server:
  enabled: true
  ha:
    enabled: true
    replicas: 3
    config: |
      ui = true
      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "file" {
        path = "/vault/data"
      }

# Disable TLS for development (enable in production)
global:
  tlsDisable: true

# Example resource limits
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"