---
# Playbook for installing and configuring Nginx and managing its firewall rules

- name: Install and configure Nginx
  hosts: nginx # Target the nginx group for webservers
  become: true

  roles:
    - role: geerlingguy.nginx

- name: Configure Firewall for Nginx
  hosts: nginx # Target the nginx group for webservers
  become: true

  vars:
    firewall_allowed_tcp_ports:
      - '22' # Keep SSH open
      - '80'
      - '443'

  roles:
    - role: firewall_state_check
      vars:
        firewall_state_check_playbook_identifier: 'nginx' # Unique identifier for this playbook
    - role: geerlingguy.firewall
      when: firewall_config_changed # Conditionally run based on the check
