---
# Playbook for installing and configuring Nginx and managing its firewall rules
- name: Install and configure Nginx and manage firewall
  hosts: nginx # Target the nginx group for webservers
  become: true

  vars:
    firewall_allowed_tcp_ports:
      - '22' # Keep SSH open
      - '80'
      - '443'

roles:
    - role: common/firewall_state_check
      vars:
        playbook_identifier: 'nginx' # Unique identifier for this playbook
    - role: geerlingguy.firewall
      when: firewall_config_changed # Conditionally run based on the check
    - role: geerlingguy.nginx
