---
# This playbook orchestrates the deployment of various roles across the infrastructure.
- name: Apply basic security hardening
  hosts: all # Or a specific group if not all servers need this
  become: true

  vars:
    security_ssh_port: 22
    security_ssh_allowed_users:
      - ansible
    security_sudoers_passwordless:
      - ansible # Assuming passwordless sudo for ansible user
    firewall_allowed_tcp_ports:
      - "22"

  roles:
    - role: geerlingguy.security
    - role: geerlingguy.firewall