name: CI - Lint, Build and Test All Workspaces

on:
  push:
    branches:
      - '**' # Run on all branches
  pull_request:
    branches:
      - '**' # Run on all branches

jobs:
  setup:
    uses: ./.github/workflows/shared-base.yml
    secrets: inherit
    with:
      node-version: 24
  lint-build-and-test:
    runs-on: ${{ matrix.os }}
    needs: [setup]
    strategy:
      matrix:
        os: [ubuntu-latest]

    environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'accept' && 'accept' || 'dev' }}
    env:
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      VAULT_ADDR: ${{ vars.VAULT_ADDR }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      ENV_NAME: ${{vars.ENV_NAME}}
      TF_VAR_backend_pg_conn_str: ${{ secrets.TF_VAR_BACKEND_PG_CONN_STR }}
      TF_VAR_proxmox_node_name: ${{ vars.TF_VAR_PROXMOX_NODE_NAME }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2 # fetch the parent commit in order to filter

      ## PNPM STUFF 
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Get pnpm store path
        id: pnpm-cache-restore
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache-restore.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }} # Removed suffix as it's not passed from shared-base
          restore-keys: |
            ${{ runner.os }}-pnpm-


      ## NODE ISNTALL STUFF
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml # Ensure this points to your monorepo's lockfile


      ## Install linters that are not installed by pnpm scripts
      - name: Install actionlint
        uses: raven-actions/actionlint@v2

      - name: Install TFLint
        uses: terraform-linters/setup-tflint@v4

      ## Install tofu
      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_wrapper: false


      - name: Run Turborepo Lint (Affected)
        run: npx turbo run lint --filter="[HEAD^1...HEAD]"

      - name: Run Turborepo Check Types (Affected)
        run: npx turbo run check-types --filter="[HEAD^1...HEAD]"

      - name: Run Turborepo Build (Affected)
        run: npx turbo run build --filter="[HEAD^1...HEAD]"

      - name: Run Turborepo Test (Affected)
        run: npx turbo run test --filter="[HEAD^1...HEAD]"

      - name: Upload Application Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-dist-artifacts
          path: |
            apps/*/dist
            packages/*/dist
          retention-days: 1