name: CI - Lint, Build and Test All Workspaces

on:
  push:
    branches:
      - '**' # Run on all branches
  pull_request:
    branches:
      - '**' # Run on all branches

jobs:
  lint-build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'accept' && 'accept' || 'dev' }}
    env:
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      VAULT_ADDR: ${{ vars.VAULT_ADDR }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      ENV_NAME: ${{vars.ENV_NAME}}
      TF_VAR_backend_pg_conn_str: ${{ secrets.TF_VAR_BACKEND_PG_CONN_STR }}
      TF_VAR_proxmox_node_name: ${{ secrets.TF_VAR_PROXMOX_NODE_NAME }}

    steps:
      - name: Call Reusable Setup
        uses: ./.github/workflows/shared-base-install.yml
        with:
          node-version: '24'

      - name: Install TFLint
        uses: terraform-linters/setup-tflint@v4
      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_wrapper: false
      - name: Add tofu to PATH
        run: echo "/home/runner/.opentofu/bin" >> $GITHUB_PATH

      - name: Run Turborepo Lint (Affected)
        run: npx turbo run lint --filter="[HEAD^1...HEAD]"

      - name: Run Turborepo Check Types (Affected)
        run: npx turbo run check-types --filter="[HEAD^1...HEAD]"

      - name: Run Turborepo Build (Affected)
        run: npx turbo run build --filter="[HEAD^1...HEAD]"

      - name: Run Turborepo Test (Affected)
        run: npx turbo run test --filter="[HEAD^1...HEAD]"

      - name: Upload Application Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-dist-artifacts
          path: |
            apps/*/dist
            packages/*/dist
          retention-days: 1